server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  profiles:
    active: jwt
  cloud:
    gateway:
        routes:
            - id: AUTH-SERVER
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - AuthenticationFilter

restclient:
  baseuri: http://localhost:8082

logging:
  level:
    feign: DEBUG
